-- Insert sample properties for demonstration
INSERT INTO public.properties (
  title, 
  description, 
  property_type, 
  transaction_type, 
  price, 
  price_per_sqm, 
  area, 
  rooms, 
  floor, 
  total_floors, 
  building_year, 
  condition, 
  city, 
  district, 
  address,
  features,
  status
) VALUES 
-- Kyiv properties
(
  'Luxury Penthouse with Panoramic City View',
  'Exclusive penthouse apartment with stunning panoramic views of the city. This modern property features high-end finishes, floor-to-ceiling windows, and an open-plan layout. Perfect for those seeking luxury living in the heart of Kyiv.',
  'apartment',
  'sale',
  8500000,
  65385,
  130,
  3,
  15,
  16,
  2022,
  'new',
  'Kyiv',
  'Pechersk',
  '15 Druzhby Narodiv Blvd',
  '["parking", "24/7 security", "elevator", "balcony", "central heating", "air conditioning", "furnished", "smart home"]'::jsonb,
  'active'
),
(
  'Modern Office Space in Business Center',
  'Premium office space located in a prestigious business center. Features modern infrastructure, professional reception, parking facilities, and excellent transport accessibility.',
  'office',
  'sale',
  12000000,
  40000,
  300,
  null,
  8,
  20,
  2021,
  'new',
  'Kyiv',
  'Podil',
  '42 Naberezhno-Khreshchatytska St',
  '["parking", "24/7 security", "elevator", "central heating", "air conditioning"]'::jsonb,
  'active'
),
(
  'Cozy 2-Room Apartment in Obolon',
  'Comfortable two-room apartment in a quiet area with developed infrastructure. Close to metro, shopping centers, parks and schools. Perfect for a young family.',
  'apartment',
  'sale',
  2850000,
  48305,
  59,
  2,
  7,
  14,
  2018,
  'good',
  'Kyiv',
  'Obolon',
  '8 Heroiv Dnipra St',
  '["parking", "elevator", "balcony", "central heating"]'::jsonb,
  'active'
),
-- Kharkiv properties
(
  'Spacious 3-Room Apartment',
  'Large three-room apartment in the central district of Kharkiv. High ceilings, separate rooms, two balconies. Walking distance to all necessary infrastructure.',
  'apartment',
  'sale',
  4200000,
  48000,
  87.5,
  3,
  7,
  12,
  2019,
  'renovated',
  'Kharkiv',
  'Saltivka',
  '156 Akademika Pavlova St',
  '["parking", "elevator", "balcony", "central heating", "renovated"]'::jsonb,
  'active'
),
(
  'Modern Studio Near Metro',
  'Brand new studio apartment in a modern residential complex. Smart layout, quality finishing, built-in furniture. Metro station just 3 minutes walk.',
  'apartment',
  'sale',
  1920000,
  54857,
  35,
  1,
  5,
  16,
  2023,
  'new',
  'Kharkiv',
  'Kyivskyi',
  '22 Heroiv Pratsi St',
  '["parking", "24/7 security", "elevator", "central heating", "air conditioning", "furnished"]'::jsonb,
  'active'
),
-- Odesa properties
(
  'Cozy Studio Near Metro',
  'Perfect studio apartment near the sea. Modern design, quality appliances, walking distance to beaches and entertainment. Ideal for investment or personal use.',
  'apartment',
  'sale',
  1850000,
  52857,
  35,
  1,
  3,
  10,
  2020,
  'renovated',
  'Odesa',
  'Arcadia',
  '15 Arcadia Ave',
  '["parking", "elevator", "balcony", "central heating", "sea view"]'::jsonb,
  'active'
),
(
  'Sea View Apartment 2 Rooms',
  'Beautiful apartment with sea view. Two separate bedrooms, spacious living room, modern kitchen. Close to beach, restaurants and entertainment.',
  'apartment',
  'sale',
  3750000,
  53571,
  70,
  2,
  8,
  9,
  2019,
  'good',
  'Odesa',
  'Center',
  '43 Deribasivska St',
  '["parking", "elevator", "balcony", "central heating", "sea view"]'::jsonb,
  'active'
),
-- Dnipro properties
(
  'Premium Office with Parking',
  'Exceptional office space in the heart of Dnipro business district. Panoramic windows, premium finishes, dedicated parking spaces. Ready for immediate occupancy.',
  'office',
  'sale',
  18500000,
  37000,
  500,
  null,
  12,
  25,
  2022,
  'new',
  'Dnipro',
  'Center',
  '88 Dmytra Yavornytskoho Ave',
  '["parking", "24/7 security", "elevator", "central heating", "air conditioning", "smart building"]'::jsonb,
  'active'
),
(
  'Comfortable 2-Room Apartment',
  'Well-maintained apartment in a quiet residential area. Quality renovation, modern furniture and appliances. Close to schools, kindergartens and shops.',
  'apartment',
  'sale',
  2650000,
  47321,
  56,
  2,
  4,
  9,
  2017,
  'renovated',
  'Dnipro',
  'Sobornyi',
  '12 Nauky Ave',
  '["parking", "elevator", "balcony", "central heating", "renovated"]'::jsonb,
  'active'
),
-- Lviv properties
(
  'Renovated 2-Room Apartment',
  'Charming apartment in the historic center of Lviv. Quality European-style renovation, high ceilings, original architectural elements. Walking distance to all attractions.',
  'apartment',
  'sale',
  3250000,
  50000,
  65,
  2,
  5,
  9,
  2016,
  'renovated',
  'Lviv',
  'Sykhiv',
  '28 Shevchenka Ave',
  '["parking", "elevator", "balcony", "central heating", "renovated"]'::jsonb,
  'active'
),
(
  'Modern 1-Room Apartment',
  'Contemporary one-room apartment in new residential complex. Smart layout, quality materials, underground parking. Great for young professionals.',
  'apartment',
  'sale',
  2180000,
  54500,
  40,
  1,
  6,
  15,
  2023,
  'new',
  'Lviv',
  'Frankivskyi',
  '45 Mazepy St',
  '["parking", "24/7 security", "elevator", "central heating", "air conditioning"]'::jsonb,
  'active'
),
(
  'Business Center Office Space',
  'Modern office in class A business center. Professional infrastructure, excellent location, parking included. Perfect for IT companies and startups.',
  'office',
  'sale',
  9500000,
  38000,
  250,
  null,
  7,
  15,
  2021,
  'new',
  'Lviv',
  'Center',
  '12 Horodotska St',
  '["parking", "24/7 security", "elevator", "central heating", "air conditioning"]'::jsonb,
  'active'
);